// web/src/components/ConnectDialog.vue
<script setup lang="ts">
import { confirmAction } from '../lib/desktop'
import { computed, reactive, ref } from 'vue'
import {
  CodeXml,
  Database,
  Eye,
  EyeOff,
  Lock,
  Plug,
  Power,
  Server,
  SlidersHorizontal,
  User,
  X,
} from 'lucide-vue-next'
import { useConnection, type SavedConnection } from '../composables/connection'
import type { ConnectionConfig } from '../types'

const conn = useConnection()
const saved = conn.saved()
const mode = ref<'params' | 'url'>('params')
const remember = ref(true)
const showPassword = ref(false)

const form = reactive<ConnectionConfig>({
  host: 'localhost',
  port: 5432,
  database: '',
  user: 'postgres',
  password: '',
  ssl: false,
})
const url = ref('')

const hasLeftColumn = computed(() => conn.state.id !== null || saved.length > 0)

interface ConnectionRow {
  label: string
  sub: string
  saved: SavedConnection | null
  /** Currently connected — highlighted, and its action is Disconnect. */
  active: boolean
  /** Stable number shown for saved connections; null for an unsaved active one. */
  seq: number | null
}

/** Saved connections plus a synthetic row when connected without remembering. */
const allConnections = computed<ConnectionRow[]>(() => {
  const items: ConnectionRow[] = saved.map((c) => ({
    label: c.label,
    sub: c.connectionString ? 'connection string' : `${c.host}:${c.port} • ${c.database}`,
    saved: c,
    active: c.label === conn.state.label,
    seq: c.seq,
  }))
  if (conn.state.id && !items.some((item) => item.active)) {
    items.unshift({ label: conn.state.label, sub: '', saved: null, active: true, seq: null })
  }
  return items
})

function pick(c: SavedConnection) {
  conn.state.error = ''
  if (c.connectionString) {
    mode.value = 'url'
    url.value = c.connectionString
  } else {
    mode.value = 'params'
    form.host = c.host ?? 'localhost'
    form.port = c.port ?? 5432
    form.database = c.database ?? ''
    form.user = c.user ?? 'postgres'
    form.password = c.password ?? ''
    form.ssl = c.ssl ?? false
  }
}

function drop(label: string) {
  conn.forget(label)
}

async function clearAll() {
  if (!saved.length) return
  if (await confirmAction('Forget all saved connections?')) conn.forgetAll()
}

async function submit() {
  if (mode.value === 'url' && !url.value.trim()) {
    conn.state.error = 'Connection string is required'
    return
  }
  const cfg: ConnectionConfig =
    mode.value === 'url'
      ? { connectionString: url.value.trim() }
      : { ...form, port: Number(form.port) || 5432 }
  await conn.connect(cfg, remember.value)
}
</script>

<template>
  <div class="modal-backdrop" @click.self="conn.state.dialog = false">
    <div class="modal connect-modal">
      <button class="icon connect-close" title="Close" @click="conn.state.dialog = false">
        <X :size="16" />
      </button>

      <div class="connect-head">
        <div class="connect-logo"><Database :size="30" /></div>
        <div>
          <h2>Connect to PostgreSQL</h2>
          <p class="connect-sub">Connect to a PostgreSQL database to explore and query your data.</p>
        </div>
      </div>

      <div class="connect-cols" :class="{ single: !hasLeftColumn }">
        <div v-if="hasLeftColumn" class="connect-panel">
          <div class="recent-head">
            <h3 class="panel-title">Connections</h3>
            <button v-if="saved.length" class="link" @click="clearAll">Clear all</button>
          </div>
          <div class="saved">
            <div
              v-for="c in allConnections"
              :key="c.label"
              class="saved-item"
              :class="{ current: c.active }"
              @click="c.saved && pick(c.saved)"
            >
              <Database class="saved-icon" :size="17" />
              <span v-if="c.seq !== null" class="saved-seq" :title="`Connection #${c.seq}`">#{{ c.seq }}</span>
              <span class="saved-text">
                <strong>{{ c.label }}</strong>
                <small v-if="c.sub">{{ c.sub }}</small>
              </span>
              <!-- Tab-sized action buttons: disconnect for the active
                   connection, forget (X) for everything else. -->
              <button
                v-if="c.active"
                class="row-action disconnect"
                title="Disconnect"
                :disabled="conn.state.connecting"
                @click.stop="conn.disconnect()"
              >
                <Power :size="14" />
              </button>
              <button
                v-else-if="c.saved"
                class="row-action"
                title="Forget"
                @click.stop="drop(c.saved.label)"
              >
                <X :size="14" />
              </button>
            </div>
          </div>
        </div>

        <div class="connect-panel">
          <h3 class="panel-title">New connection</h3>

          <div class="seg" role="tablist">
            <button
              type="button"
              class="seg-btn"
              :class="{ active: mode === 'params' }"
              role="tab"
              :aria-selected="mode === 'params'"
              @click="mode = 'params'"
            >
              <SlidersHorizontal :size="14" /> Parameters
            </button>
            <button
              type="button"
              class="seg-btn"
              :class="{ active: mode === 'url' }"
              role="tab"
              :aria-selected="mode === 'url'"
              @click="mode = 'url'"
            >
              <CodeXml :size="14" /> Connection string
            </button>
          </div>

          <form v-if="mode === 'params'" class="fields" @submit.prevent="submit">
            <label class="field-label">
              <span>Host</span>
              <span class="field"><Server class="field-icon" :size="14" /><input v-model="form.host" /></span>
            </label>
            <label class="field-label">
              <span>Port</span>
              <span class="field"><input v-model.number="form.port" type="number" /></span>
            </label>
            <label class="field-label">
              <span>Database</span>
              <span class="field"><Database class="field-icon" :size="14" /><input v-model="form.database" required placeholder="postgres" /></span>
            </label>
            <label class="field-label">
              <span>User</span>
              <span class="field"><User class="field-icon" :size="14" /><input v-model="form.user" /></span>
            </label>
            <label class="field-label">
              <span>Password</span>
              <span class="field">
                <Lock class="field-icon" :size="14" />
                <input
                  v-model="form.password"
                  :type="showPassword ? 'text' : 'password'"
                  autocomplete="off"
                  placeholder="Enter password"
                />
                <button
                  type="button"
                  class="icon field-eye"
                  :title="showPassword ? 'Hide password' : 'Show password'"
                  @click.prevent="showPassword = !showPassword"
                >
                  <EyeOff v-if="showPassword" :size="14" />
                  <Eye v-else :size="14" />
                </button>
              </span>
            </label>

            <div class="checks">
              <label class="check-item">
                <input v-model="form.ssl" type="checkbox" />
                <span><strong>SSL</strong><small>Use SSL to connect to the database</small></span>
              </label>
              <label class="check-item">
                <input v-model="remember" type="checkbox" />
                <span><strong>Remember on this device</strong><small>Credentials use secure OS storage when available</small></span>
              </label>
            </div>

            <button class="primary connect-btn" type="submit" :disabled="conn.state.connecting">
              <Plug :size="15" />
              {{ conn.state.connecting ? 'Connecting…' : 'Connect' }}
            </button>
          </form>

          <form v-else class="fields" @submit.prevent="submit">
            <label class="field-label">
              <span>URL</span>
              <span class="field"><input v-model="url" placeholder="postgres://user:pass@host:5432/db" /></span>
            </label>
            <div class="checks">
              <label class="check-item">
                <input v-model="remember" type="checkbox" />
                <span><strong>Remember on this device</strong><small>Credentials use secure OS storage when available</small></span>
              </label>
            </div>
            <button class="primary connect-btn" type="submit" :disabled="conn.state.connecting">
              <Plug :size="15" />
              {{ conn.state.connecting ? 'Connecting…' : 'Connect' }}
            </button>
          </form>

          <div v-if="conn.state.error" class="error">{{ conn.state.error }}</div>
        </div>
      </div>
    </div>
  </div>
</template>

// web/src/components/ConnectDialog.svelte
<script lang="ts">
  import { CodeXml, Database, Eye, EyeOff, Lock, Plug, Power, Server, SlidersHorizontal, User, X } from '@lucide/svelte'
  import { useConnection, type SavedConnection } from '../composables/connection'
  import { confirmAction } from '../lib/desktop'
  import { stateView } from '../lib/state.svelte'
  import type { ConnectionConfig } from '../types'

  const conn = useConnection()
  const saved = conn.saved()
  const snapshot = stateView(() => ({ ...conn.state, saved: saved.map((entry) => ({ ...entry })) }))
  let mode = $state<'params' | 'url'>('params')
  let remember = $state(true)
  let showPassword = $state(false)
  let url = $state('')
  const form = $state<ConnectionConfig>({
    host: 'localhost', port: 5432, database: '', user: 'postgres', password: '', ssl: false,
  })

  interface ConnectionRow {
    label: string
    sub: string
    saved: SavedConnection | null
    active: boolean
    seq: number | null
  }

  const hasLeftColumn = $derived(snapshot.current.id !== null || snapshot.current.saved.length > 0)
  const allConnections = $derived.by(() => {
    const items: ConnectionRow[] = snapshot.current.saved.map((entry) => ({
      label: entry.label,
      sub: entry.connectionString ? 'connection string' : `${entry.host}:${entry.port} • ${entry.database}`,
      saved: entry,
      active: entry.label === snapshot.current.label,
      seq: entry.seq,
    }))
    if (snapshot.current.id && !items.some((item) => item.active)) {
      items.unshift({ label: snapshot.current.label, sub: '', saved: null, active: true, seq: null })
    }
    return items
  })

  function pick(entry: SavedConnection) {
    conn.state.error = ''
    if (entry.connectionString) {
      mode = 'url'
      url = entry.connectionString
    } else {
      mode = 'params'
      form.host = entry.host ?? 'localhost'
      form.port = entry.port ?? 5432
      form.database = entry.database ?? ''
      form.user = entry.user ?? 'postgres'
      form.password = entry.password ?? ''
      form.ssl = entry.ssl ?? false
    }
  }

  function pickWithKeyboard(event: KeyboardEvent, entry: SavedConnection | null) {
    if (event.target !== event.currentTarget || !entry) return
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault()
      pick(entry)
    }
  }

  async function clearAll() {
    if (!saved.length) return
    if (await confirmAction('Forget all saved connections?')) conn.forgetAll()
  }

  async function submit(event: SubmitEvent) {
    event.preventDefault()
    if (mode === 'url' && !url.trim()) {
      conn.state.error = 'Connection string is required'
      return
    }
    const config: ConnectionConfig = mode === 'url'
      ? { connectionString: url.trim() }
      : { ...form, port: Number(form.port) || 5432 }
    await conn.connect(config, remember)
  }

  function close() { conn.state.dialog = false }
</script>

<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
<div class="modal-backdrop" onclick={(event) => { if (event.target === event.currentTarget) close() }}>
  <div class="modal connect-modal" role="dialog" aria-modal="true" aria-label="Connect to PostgreSQL" tabindex="-1">
    <button class="icon connect-close" title="Close" onclick={close}><X size={16} /></button>
    <div class="connect-head">
      <div class="connect-logo"><Database size={30} /></div>
      <div>
        <h2>Connect to PostgreSQL</h2>
        <p class="connect-sub">Connect to a PostgreSQL database to explore and query your data.</p>
      </div>
    </div>
    <div class="connect-cols" class:single={!hasLeftColumn}>
      {#if hasLeftColumn}
        <div class="connect-panel">
          <div class="recent-head">
            <h3 class="panel-title">Connections</h3>
            {#if snapshot.current.saved.length}<button class="link" onclick={clearAll}>Clear all</button>{/if}
          </div>
          <div class="saved">
            {#each allConnections as entry (entry.label)}
              <div class="saved-item" class:current={entry.active} role="button" tabindex={entry.saved ? 0 : -1}
                aria-label={entry.label} onclick={() => { if (entry.saved) pick(entry.saved) }}
                onkeydown={(event) => pickWithKeyboard(event, entry.saved)}>
                <Database class="saved-icon" size={17} />
                {#if entry.seq !== null}<span class="saved-seq" title={`Connection #${entry.seq}`}>#{entry.seq}</span>{/if}
                <span class="saved-text"><strong>{entry.label}</strong>{#if entry.sub}<small>{entry.sub}</small>{/if}</span>
                {#if entry.active}
                  <button class="row-action disconnect" title="Disconnect" disabled={snapshot.current.connecting}
                    onclick={(event) => { event.stopPropagation(); void conn.disconnect() }}><Power size={14} /></button>
                {:else if entry.saved}
                  <button class="row-action" title="Forget"
                    onclick={(event) => { event.stopPropagation(); conn.forget(entry.label) }}><X size={14} /></button>
                {/if}
              </div>
            {/each}
          </div>
        </div>
      {/if}
      <div class="connect-panel">
        <h3 class="panel-title">New connection</h3>
        <div class="seg" role="tablist" aria-label="Connection format">
          <button type="button" class="seg-btn" class:active={mode === 'params'} role="tab"
            aria-selected={mode === 'params'} onclick={() => { mode = 'params' }}><SlidersHorizontal size={14} /> Parameters</button>
          <button type="button" class="seg-btn" class:active={mode === 'url'} role="tab"
            aria-selected={mode === 'url'} onclick={() => { mode = 'url' }}><CodeXml size={14} /> Connection string</button>
        </div>
        {#if mode === 'params'}
          <form class="fields" onsubmit={submit}>
            <label class="field-label"><span>Host</span><span class="field"><Server class="field-icon" size={14} /><input bind:value={form.host} /></span></label>
            <label class="field-label"><span>Port</span><span class="field"><input bind:value={form.port} type="number" /></span></label>
            <label class="field-label"><span>Database</span><span class="field"><Database class="field-icon" size={14} /><input bind:value={form.database} required placeholder="postgres" /></span></label>
            <label class="field-label"><span>User</span><span class="field"><User class="field-icon" size={14} /><input bind:value={form.user} /></span></label>
            <label class="field-label">
              <span>Password</span>
              <span class="field">
                <Lock class="field-icon" size={14} />
                <input bind:value={form.password} type={showPassword ? 'text' : 'password'} autocomplete="off" placeholder="Enter password" />
                <button type="button" class="icon field-eye" title={showPassword ? 'Hide password' : 'Show password'}
                  onclick={() => { showPassword = !showPassword }}>
                  {#if showPassword}<EyeOff size={14} />{:else}<Eye size={14} />{/if}
                </button>
              </span>
            </label>
            <div class="checks">
              <label class="check-item"><input bind:checked={form.ssl} type="checkbox" /><span><strong>SSL</strong><small>Use SSL to connect to the database</small></span></label>
              <label class="check-item"><input bind:checked={remember} type="checkbox" /><span><strong>Remember on this device</strong><small>Credentials use secure OS storage when available</small></span></label>
            </div>
            <button class="primary connect-btn" type="submit" disabled={snapshot.current.connecting}><Plug size={15} />{snapshot.current.connecting ? 'Connecting…' : 'Connect'}</button>
          </form>
        {:else}
          <form class="fields" onsubmit={submit}>
            <label class="field-label"><span>URL</span><span class="field"><input bind:value={url} placeholder="postgres://user:pass@host:5432/db" /></span></label>
            <div class="checks">
              <label class="check-item"><input bind:checked={remember} type="checkbox" /><span><strong>Remember on this device</strong><small>Credentials use secure OS storage when available</small></span></label>
            </div>
            <button class="primary connect-btn" type="submit" disabled={snapshot.current.connecting}><Plug size={15} />{snapshot.current.connecting ? 'Connecting…' : 'Connect'}</button>
          </form>
        {/if}
        {#if snapshot.current.error}<div class="error">{snapshot.current.error}</div>{/if}
      </div>
    </div>
  </div>
</div>
