// web/src/components/ResultsPanel.vue
<script setup lang="ts">
import { computed, inject, onBeforeUnmount, reactive, ref, watch } from 'vue'
import { Copy, Download, Pencil, Play, Square } from 'lucide-vue-next'
import { useResults } from '../composables/results'
import { useConnection } from '../composables/connection'
import { useTabs } from '../composables/tabs'
import { useToast } from '../composables/toast'
import { copyGrid, copyText, csvHeader, csvRows, formatCellForDisplay } from '../lib/gridio'
import { createOutput } from '../lib/files'
import ValueDialog, { type CellValueTarget } from './ValueDialog.vue'
import RowEditDialog, { type RowEditTarget } from './RowEditDialog.vue'

const results = useResults()
const conn = useConnection()
const tabs = useTabs()
const toast = useToast()
const run = inject<(sql?: string) => void>('pgdev:run')

const result = computed(() => results.state.byTab[tabs.state.activeKey] ?? null)
const activeGrid = computed(() =>
  result.value && !result.value.showMessages ? result.value.grid : null,
)
const activeTab = computed(
  () => tabs.state.tabs.find((t) => t.key === tabs.state.activeKey) ?? null,
)
/** Row editing is only for editable grids in an editable tab: the read-only AI
 * log never offers it, whatever metadata its mirrored grid might carry. */
const rowEditable = computed(() => !!activeGrid.value?.editable && activeTab.value?.readOnly !== true)

function showMessagesView() {
  if (result.value) result.value.showMessages = true
}

const ROW_H = 24
const HEADER_H = 24
const COL_W = 180
/** Width of the per-row edit button column (only for editable results). */
const ACTION_W = 30
const bodyEl = ref<HTMLElement | null>(null)
const scrollTop = ref(0)
const bodyH = ref(300)
let observer: ResizeObserver | null = null

const widthsByKey = reactive(new Map<string, number[]>())
const columnsByKey = reactive(new Map<string, string[]>())
let dragCol = -1
let dragStartX = 0
let dragStartW = 0

function colWidth(i: number): number {
  const key = activeGrid.value?.key ?? ''
  return widthsByKey.get(key)?.[i] ?? COL_W
}

function ensureWidths(key: string, columns: string[]) {
  const arr = widthsByKey.get(key)
  const prev = columnsByKey.get(key)
  const same =
    arr &&
    prev &&
    arr.length === columns.length &&
    prev.length === columns.length &&
    prev.every((c, i) => c === columns[i])
  if (!same) {
    widthsByKey.set(
      key,
      Array.from({ length: columns.length }, () => COL_W),
    )
    columnsByKey.set(key, [...columns])
  }
}

const innerWidth = computed(() => {
  const g = activeGrid.value
  if (!g) return 0
  const columns = g.columns.reduce((sum, _c, i) => sum + colWidth(i), 0)
  return columns + (rowEditable.value ? ACTION_W : 0)
})

function startResize(i: number, e: MouseEvent) {
  e.preventDefault()
  e.stopPropagation()
  dragCol = i
  dragStartX = e.clientX
  dragStartW = colWidth(i)
  window.addEventListener('mousemove', onResizeMove)
  window.addEventListener('mouseup', endResize)
}

function onResizeMove(e: MouseEvent) {
  if (dragCol < 0) return
  const arr = widthsByKey.get(activeGrid.value?.key ?? '')
  if (arr) arr[dragCol] = Math.max(60, Math.min(1200, dragStartW + e.clientX - dragStartX))
}

function endResize() {
  dragCol = -1
  window.removeEventListener('mousemove', onResizeMove)
  window.removeEventListener('mouseup', endResize)
}

watch(bodyEl, (el) => {
  observer?.disconnect()
  observer = null
  if (el) {
    bodyH.value = el.clientHeight
    observer = new ResizeObserver((entries) => {
      bodyH.value = entries[0]?.contentRect.height ?? 300
    })
    observer.observe(el)
  }
})

watch(
  () => activeGrid.value,
  (g) => {
    endResize()
    scrollTop.value = 0
    if (bodyEl.value) bodyEl.value.scrollTop = 0
    if (g) ensureWidths(g.key, g.columns)
  },
)

watch(
  () => tabs.state.tabs.map((t) => t.key),
  (keys) => {
    const set = new Set(keys)
    for (const key of Object.keys(results.state.byTab)) {
      if (!set.has(key)) results.drop(key)
    }
  },
)

watch(
  () => Object.values(results.state.byTab).flatMap((r) => r.grids.map((g) => g.key)),
  (keys) => {
    const live = new Set(keys)
    for (const key of widthsByKey.keys()) {
      if (!live.has(key)) {
        widthsByKey.delete(key)
        columnsByKey.delete(key)
      }
    }
  },
)

onBeforeUnmount(() => { observer?.disconnect(); endResize() })

const grid = computed(() => {
  const g = activeGrid.value
  if (!g) return null
  const start = Math.max(0, Math.floor(scrollTop.value / ROW_H) - 5)
  const visible = Math.ceil(bodyH.value / ROW_H) + 10
  return { g, start, rows: g.rows.slice(start, start + visible) }
})

function onScroll() {
  if (bodyEl.value) scrollTop.value = bodyEl.value.scrollTop
}

function fmt(v: unknown): string {
  return formatCellForDisplay(v)
}

/** Double-click behaviour: JSON/JSONB cells open the value dialog (pretty
 * printed, with its own COPY), everything else copies straight to the
 * clipboard like it used to. NULL stays inert — the badge says it all. */
const cellValue = ref<CellValueTarget | null>(null)

const rowEdit = ref<RowEditTarget | null>(null)

/** A row is editable only when every key cell actually holds a value; a NULL
 * key could not name a row in the WHERE clause. */
function rowKeyComplete(r: unknown[]): boolean {
  const g = activeGrid.value
  if (!rowEditable.value || !g?.editable) return false
  for (const pk of g.editable.pk) {
    const j = g.columns.indexOf(pk)
    if (j < 0 || r[j] === null || r[j] === undefined) return false
  }
  return true
}

function openRowEdit(r: unknown[]) {
  const g = activeGrid.value
  if (!rowEditable.value || !g?.editable || !conn.state.id) return
  rowEdit.value = {
    grid: g,
    row: r,
    connectionId: conn.state.id,
    tabKey: tabs.state.activeKey,
    transactionId: result.value?.transactionId ?? null,
  }
}

/** Patch the stored row (UPDATE … RETURNING *) into the loaded cells. Only
 * matching names are touched — expressions simply stay as they were. */
function onRowSaved(row: Record<string, unknown>) {
  const target = rowEdit.value
  if (!target) return
  for (let j = 0; j < target.grid.columns.length; j++) {
    const name = target.grid.columns[j] ?? ''
    if (Object.prototype.hasOwnProperty.call(row, name)) target.row[j] = row[name]
  }
}

function isJsonColumn(j: number): boolean {
  const type = activeGrid.value?.columnTypes[j]
  return type === 'json' || type === 'jsonb'
}

function openCell(v: unknown, j: number) {
  if (v === null || v === undefined) return
  const g = activeGrid.value
  if (!g) return
  if (g.columnTypes[j] === 'json' || g.columnTypes[j] === 'jsonb') {
    cellValue.value = {
      column: g.columns[j] ?? '',
      type: g.columnTypes[j],
      value: typeof v === 'string' ? v : String(v),
    }
    return
  }
  void copyCell(v)
}

async function copyCell(v: unknown) {
  const ok = await copyText(typeof v === 'string' ? v : String(v))
  toast.show(ok ? 'Value copied.' : 'Copy to clipboard failed')
}

function cancelRun() {
  if (!conn.state.id || (!result.value?.running && !result.value?.loadingMore)) return
  results.cancel(tabs.state.activeKey, conn.state.id)
  toast.show(result.value.loadingMore ? 'Canceling row load…' : 'Canceling query…')
}

function loadMoreRows() {
  if (!conn.state.id || !result.value?.grid?.truncated) return
  results.loadMore(tabs.state.activeKey, conn.state.id)
}

/** Commit/Rollback run through the normal run path for the active tab, so the
 * per-tab running guard, messages and session release all apply. */
function runControl(sql: 'COMMIT' | 'ROLLBACK') {
  if (!conn.state.id || result.value?.running || result.value?.loadingMore) return
  results.run(tabs.state.activeKey, conn.state.id, sql)
}

async function copyResult() {
  const g = activeGrid.value
  if (!g) return
  const ok = await copyGrid(g.columns, g.rows)
  toast.show(ok ? `Copied ${g.rows.length} row(s) to clipboard` : 'Copy to clipboard failed')
}

async function exportCsv() {
  const connectionId = conn.state.id
  if (!connectionId) return
  const tabKey = tabs.state.activeKey
  // The grid is captured here, before any await: the save picker and the
  // drain run later, and a selection change meanwhile must not switch what
  // gets exported (the store re-validates this capture every step).
  const g = results.state.byTab[tabKey]?.grid
  if (!g) return
  // A consumed cursor cannot be drained twice, and an interrupted drain loses
  // cursor pages: both require a re-run instead of a silent partial file.
  // Read once into a local so later property checks are not narrowed away.
  const priorExport = g.exported
  if (priorExport?.incomplete) {
    toast.show('Export interrupted — re-run the query to export again')
    return
  }
  if (priorExport) {
    toast.show('Already exported — re-run the query to export again')
    return
  }
  const stamp = new Date().toISOString().replace(/[:T]/g, '-').slice(0, 19)
  const filename = `pgDEV-statement-${g.statementNumber}-${stamp}${g.limited ? '-partial' : ''}.csv`

  // Stream pages straight to native disk: memory stays flat
  // (drained pages are not retained in the grid) and every write is awaited
  // so a failed write aborts the file instead of vanishing into a void.
  {
    let output
    try {
      output = await createOutput(filename, undefined, true)
    } catch (e) {
      if ((e as Error).name !== 'AbortError') toast.show(`Export failed: ${(e as Error).message}`)
      return
    }
    if (!output) return
    const writable = output.writable
    let rows = 0
    try {
      await writable.write(csvHeader(g.columns))
      const complete = await results.exportAll(tabKey, connectionId, g, async (page) => {
        rows += page.length
        await writable.write(csvRows(page))
      }, false)
      if (!complete) {
        // Stale drain, failed write or cancel: discard the partial file
        // rather than leaving truncated data on disk.
        await writable.abort()
        toast.show(g.exported?.incomplete
          ? 'Export interrupted — re-run the query to export again'
          : 'Export canceled because the connection or result changed')
        return
      }
      await writable.close()
      toast.show(g.limited
        ? `Exported first ${rows} of ${g.totalRowCount} rows to CSV (partial result)`
        : `Exported ${rows} row(s) to CSV`)
    } catch (e) {
      await writable.abort().catch(() => undefined)
      toast.show(`Export failed: ${(e as Error).message}`)
    }
    return
  }

}
</script>

<template>
  <div class="results">
    <div class="results-head">
      <div class="subtabs">
        <button
          v-for="(g, index) in result?.grids ?? []"
          :key="g.key"
          class="subtab"
          :class="{ active: !result?.showMessages && result?.grid?.key === g.key }"
          :aria-pressed="!result?.showMessages && result?.grid?.key === g.key"
          :title="`Statement ${g.statementNumber} · ${g.rows.length} loaded row(s)${g.limited ? ' · partial result' : ''}`"
          @click="results.selectGrid(tabs.state.activeKey, g.key)"
        >
          Result {{ index + 1 }}
        </button>
        <button
          class="subtab"
          :class="{ active: !result || result.showMessages }"
          @click="showMessagesView()"
        >
          Messages
        </button>
      </div>
      <span class="spacer" />
      <template v-if="result?.transactionOpen">
        <span class="txn-badge" title="A manual transaction is open for this tab">TXN</span>
        <button
          class="btn-sm commit"
          :disabled="result?.running || result?.loadingMore"
          title="Commit the open transaction"
          @click="runControl('COMMIT')"
        >COMMIT</button>
        <button
          class="btn-sm danger"
          :disabled="result?.running || result?.loadingMore"
          title="Roll back the open transaction"
          @click="runControl('ROLLBACK')"
        >ROLLBACK</button>
      </template>
      <template v-if="activeGrid">
        <button class="btn-sm" title="Copy loaded rows to clipboard (TSV)" :disabled="result?.loadingMore" @click="copyResult()"><Copy :size="13" /> COPY</button>
        <button class="btn-sm" :title="activeGrid.limited ? 'Export only the retained rows to CSV (partial result)' : 'Export all rows to CSV'" :disabled="result?.loadingMore" @click="exportCsv()"><Download :size="13" /> {{ activeGrid.limited ? 'CSV (partial)' : 'CSV' }}</button>
      </template>
      <button
        v-if="result?.running || result?.loadingMore"
        class="danger"
        :disabled="result?.cancelling"
        title="Cancel running query or row load"
        @click="cancelRun()"
      >
        <Square :size="11" /> {{ result?.cancelling ? 'Canceling…' : result?.loadingMore ? 'Cancel load' : 'Cancel' }}
      </button>
      <button
        v-else
        class="primary run-btn"
        :disabled="!conn.state.id || result?.loadingMore || tabs.state.tabs.find((t) => t.key === tabs.state.activeKey)?.readOnly"
        title="Run (F5 or Ctrl+Enter)"
        @click="run?.()"
      >
        <Play :size="13" /> Run
      </button>
    </div>

    <div v-if="!result || result.showMessages || !result.grid" class="messages">
      <div v-if="!result || !result.messages.length" class="msg dim">
        Run a query to see results (F5 or Ctrl+Enter in the editor).
      </div>
      <div v-for="(m, i) in result?.messages ?? []" :key="i" class="msg" :class="m.level">
        {{ m.text }}
      </div>
    </div>

    <div v-else-if="grid" class="grid">
      <div ref="bodyEl" class="grid-body" @scroll="onScroll">
        <div class="grid-inner" :style="{ width: innerWidth + 'px' }">
          <div class="grid-head">
            <div
              v-if="rowEditable"
              class="grid-cell head actions"
              :style="{ width: ACTION_W + 'px' }"
              title="Edit a row in a dialog (needs the full primary key in the result)"
            />
            <div
              v-for="(c, i) in grid.g.columns"
              :key="`${i}-${c}`"
              class="grid-cell head"
              :style="{ width: colWidth(i) + 'px' }"
            >
              <span class="col-name">{{ c }}</span><span v-if="grid.g.columnTypes[i]" class="col-type"> ({{ grid.g.columnTypes[i] }})</span>
              <span class="col-resize-handle" title="Resize column" @mousedown="startResize(i, $event)" @click.stop />
            </div>
          </div>
          <div class="grid-spacer" :style="{ height: grid.g.rows.length * ROW_H + 'px' }" />
          <div
            v-for="(r, i) in grid.rows"
            :key="grid.start + i"
            class="grid-row"
            :style="{ top: HEADER_H + (grid.start + i) * ROW_H + 'px' }"
          >
            <div v-if="rowEditable" class="grid-cell actions" :style="{ width: ACTION_W + 'px' }">
              <button
                class="icon rowedit-open"
                :title="rowKeyComplete(r) ? 'Edit row' : 'Row key is not available'"
                :disabled="!rowKeyComplete(r)"
                @click="openRowEdit(r)"
              >
                <Pencil :size="12" />
              </button>
            </div>
            <div
              v-for="(cell, j) in r"
              :key="j"
              class="grid-cell"
              :class="{ nul: cell === null || cell === undefined }"
              :style="{ width: colWidth(j) + 'px' }"
              :title="isJsonColumn(j) ? 'Double-click to open value' : 'Double-click to copy'"
              @dblclick="openCell(cell, j)"
            >
              <span v-if="cell === null || cell === undefined" class="null-badge">null</span>
              <span
                v-else-if="grid.g.columnTypes[j] === 'boolean'"
                class="bool-badge"
                :class="cell === true || cell === 'true' ? 'true' : 'false'"
              >{{ cell === true || cell === 'true' ? 'true' : 'false' }}</span>
              <template v-else>{{ fmt(cell) }}</template>
            </div>
          </div>
        </div>
      </div>
      <div class="grid-foot">
        <!-- the result's own rowCount, not the virtualised slice actually
             rendered: grid.rows is only the visible window -->
        {{ result?.grid?.rowCount ?? 0 }} row(s)
        <span v-if="grid.g.truncated">· more available</span>
        <span v-else-if="grid.g.limited">· first {{ grid.g.rows.length }}<template v-if="grid.g.totalRowCount"> of {{ grid.g.totalRowCount }}</template> · row limit reached; remaining rows were not retained</span>
        <span v-else-if="grid.g.exported?.incomplete">· export interrupted — re-run the query</span>
        <span v-else-if="grid.g.exported">· first {{ grid.g.rows.length }} shown · {{ grid.g.exported.rows }} row(s) exported to CSV</span>
        <button
          v-if="grid.g.truncated"
          class="btn-sm"
          :disabled="result?.loadingMore"
          title="Fetch the next page of rows"
          @click="loadMoreRows()"
        >
          {{ result?.loadingMore ? 'Loading…' : 'Load more' }}
        </button>
      </div>
    </div>

    <ValueDialog v-if="cellValue" :target="cellValue" @close="cellValue = null" />
    <RowEditDialog
      v-if="rowEdit"
      :target="rowEdit"
      @saved="onRowSaved"
      @close="rowEdit = null"
    />
  </div>
</template>

// web/src/components/ResultsPanel.svelte
<script lang="ts">
  import { onDestroy, untrack } from 'svelte'
  import { SvelteMap } from 'svelte/reactivity'
  import { Copy, Download, Pencil, Play, Square } from '@lucide/svelte'
  import { useResults, type GridResult } from '../composables/results'
  import { useConnection } from '../composables/connection'
  import { useTabs } from '../composables/tabs'
  import { useToast } from '../composables/toast'
  import { copyGrid, copyText, csvHeader, csvRows, formatCellForDisplay } from '../lib/gridio'
  import { createOutput } from '../lib/files'
  import { stateView } from '../lib/state.svelte'
  import type { CellValueTarget } from '../lib/valueTarget'
  import type { RowEditTarget } from '../lib/rowEditTarget'
  import ValueDialog from './ValueDialog.svelte'
  import RowEditDialog from './RowEditDialog.svelte'

  let { onrun }: { onrun: () => void } = $props()
  const results = useResults()
  const conn = useConnection()
  const tabs = useTabs()
  const toast = useToast()
  // Snapshot metadata, not every retained row. The results store owns the
  // cursor/transaction state; only the visible row window is copied for Svelte.
  function displayGrid(grid: GridResult) {
    return { ...grid, rowLength: grid.rows.length, exported: grid.exported ? { ...grid.exported } : undefined }
  }
  const snapshot = stateView(() => {
    const result = results.state.byTab[tabs.state.activeKey]
    return {
      activeKey: tabs.state.activeKey, connectionId: conn.state.id,
      readOnly: tabs.state.tabs.find((tab) => tab.key === tabs.state.activeKey)?.readOnly,
      tabKeys: tabs.state.tabs.map((tab) => tab.key),
      gridKeys: Object.values(results.state.byTab).flatMap((result) => result.grids.map((grid) => grid.key)),
      result: result ? {
        ...result, grids: result.grids.map(displayGrid), grid: result.grid ? displayGrid(result.grid) : null,
        messages: result.messages.map((message) => ({ ...message })),
      } : null,
    }
  })
  const result = $derived(snapshot.current.result)
  const activeGrid = $derived(result && !result.showMessages ? result.grid : null)
  const activeGridKey = $derived(activeGrid?.key ?? '')
  const gridColumns = $derived(activeGrid?.columns)
  const rowEditable = $derived(!!activeGrid?.editable && snapshot.current.readOnly !== true)
  function showMessagesView() {
    const current = results.state.byTab[tabs.state.activeKey]
    if (current) current.showMessages = true
  }
  const ROW_H = 24
  const HEADER_H = 24
  const COL_W = 180
  const ACTION_W = 30
  let bodyEl = $state<HTMLElement | null>(null)
  let scrollTop = $state(0)
  let bodyH = $state(300)
  const widthsByKey = new SvelteMap<string, number[]>()
  const columnsByKey = new Map<string, string[]>()
  let dragCol = -1
  let dragStartX = 0
  let dragStartW = 0
  function colWidth(index: number) { return widthsByKey.get(activeGridKey)?.[index] ?? COL_W }
  function ensureWidths(key: string, columns: string[]) {
    const widths = widthsByKey.get(key)
    const previous = columnsByKey.get(key)
    if (!widths || !previous || widths.length !== columns.length || previous.length !== columns.length || !previous.every((column, index) => column === columns[index])) {
      widthsByKey.set(key, Array.from({ length: columns.length }, () => COL_W))
      columnsByKey.set(key, [...columns])
    }
  }
  const innerWidth = $derived(activeGrid ? activeGrid.columns.reduce((sum, _column, index) => sum + colWidth(index), 0) + (rowEditable ? ACTION_W : 0) : 0)
  function startResize(index: number, event: MouseEvent) {
    event.preventDefault()
    event.stopPropagation()
    dragCol = index
    dragStartX = event.clientX
    dragStartW = colWidth(index)
    window.addEventListener('mousemove', onResizeMove)
    window.addEventListener('mouseup', endResize)
  }
  function onResizeMove(event: MouseEvent) {
    if (dragCol < 0) return
    const widths = widthsByKey.get(activeGridKey)
    if (!widths) return
    const next = [...widths]
    next[dragCol] = Math.max(60, Math.min(1200, dragStartW + event.clientX - dragStartX))
    widthsByKey.set(activeGridKey, next)
  }
  function endResize() {
    dragCol = -1
    window.removeEventListener('mousemove', onResizeMove)
    window.removeEventListener('mouseup', endResize)
  }
  $effect(() => {
    const element = bodyEl
    if (!element) return
    bodyH = element.clientHeight
    const observer = new ResizeObserver((entries) => { bodyH = entries[0]?.contentRect.height ?? 300 })
    observer.observe(element)
    return () => observer.disconnect()
  })
  $effect(() => {
    const key = activeGridKey
    const columns = gridColumns
    untrack(() => {
      endResize()
      scrollTop = 0
      if (bodyEl) bodyEl.scrollTop = 0
      if (key && columns) ensureWidths(key, columns)
    })
  })
  $effect(() => {
    const keys = snapshot.current.tabKeys
    untrack(() => {
      const live = new Set(keys)
      for (const key of Object.keys(results.state.byTab)) if (!live.has(key)) results.drop(key)
    })
  })
  $effect(() => {
    const keys = snapshot.current.gridKeys
    untrack(() => {
      const live = new Set(keys)
      for (const key of widthsByKey.keys()) if (!live.has(key)) { widthsByKey.delete(key); columnsByKey.delete(key) }
    })
  })
  onDestroy(endResize)
  let rowRevision = $state(0)
  const grid = $derived.by(() => {
    const current = activeGrid
    if (!current) return null
    void rowRevision
    const start = Math.max(0, Math.floor(scrollTop / ROW_H) - 5)
    const visible = Math.ceil(bodyH / ROW_H) + 10
    return { g: current, start, rows: current.rows.slice(start, start + visible).map((row) => [...row]) }
  })
  let cellValue = $state<CellValueTarget | null>(null)
  let rowEdit = $state.raw<RowEditTarget | null>(null)
  function rowKeyComplete(row: unknown[]) {
    if (!rowEditable || !activeGrid?.editable) return false
    for (const key of activeGrid.editable.pk) {
      const index = activeGrid.columns.indexOf(key)
      if (index < 0 || row[index] === null || row[index] === undefined) return false
    }
    return true
  }
  function openRowEdit(index: number) {
    const current = results.state.byTab[tabs.state.activeKey]
    const grid = current?.grid
    if (!rowEditable || !grid?.editable || !conn.state.id || !grid.rows[index]) return
    rowEdit = { grid, row: grid.rows[index], connectionId: conn.state.id, tabKey: tabs.state.activeKey, transactionId: current.transactionId ?? null }
  }
  function onRowSaved(row: Record<string, unknown>) {
    if (!rowEdit) return
    for (let index = 0; index < rowEdit.grid.columns.length; index++) {
      const name = rowEdit.grid.columns[index] ?? ''
      if (Object.prototype.hasOwnProperty.call(row, name)) rowEdit.row[index] = row[name]
    }
    rowRevision++
  }
  function isJsonColumn(index: number) { return activeGrid?.columnTypes[index] === 'json' || activeGrid?.columnTypes[index] === 'jsonb' }
  function openCell(value: unknown, index: number) {
    if (value === null || value === undefined || !activeGrid) return
    if (isJsonColumn(index)) {
      cellValue = { column: activeGrid.columns[index] ?? '', type: activeGrid.columnTypes[index], value: typeof value === 'string' ? value : String(value) }
    } else void copyCell(value)
  }
  async function copyCell(value: unknown) {
    const ok = await copyText(typeof value === 'string' ? value : String(value))
    toast.show(ok ? 'Value copied.' : 'Copy to clipboard failed')
  }
  function cancelRun() {
    if (!conn.state.id || (!result?.running && !result?.loadingMore)) return
    void results.cancel(tabs.state.activeKey, conn.state.id)
    toast.show(result.loadingMore ? 'Canceling row load…' : 'Canceling query…')
  }
  function loadMoreRows() {
    if (conn.state.id && result?.grid?.truncated) void results.loadMore(tabs.state.activeKey, conn.state.id)
  }
  function runControl(sql: 'COMMIT' | 'ROLLBACK') {
    if (!conn.state.id || result?.running || result?.loadingMore) return
    void results.run(tabs.state.activeKey, conn.state.id, sql)
  }
  async function copyResult() {
    if (!activeGrid) return
    const current = activeGrid
    const ok = await copyGrid(current.columns, current.rows)
    toast.show(ok ? `Copied ${current.rows.length} row(s) to clipboard` : 'Copy to clipboard failed')
  }
  async function exportCsv() {
    const connectionId = conn.state.id
    if (!connectionId) return
    const tabKey = tabs.state.activeKey
    // Export the owning store's captured grid, never the display snapshot.
    const current = results.state.byTab[tabKey]?.grid
    if (!current) return
    const priorExport = current.exported
    if (priorExport?.incomplete) { toast.show('Export interrupted — re-run the query to export again'); return }
    if (priorExport) { toast.show('Already exported — re-run the query to export again'); return }
    const stamp = new Date().toISOString().replace(/[:T]/g, '-').slice(0, 19)
    const filename = `pgDEV-statement-${current.statementNumber}-${stamp}${current.limited ? '-partial' : ''}.csv`
    let output
    try { output = await createOutput(filename, undefined, true) }
    catch (cause) { if ((cause as Error).name !== 'AbortError') toast.show(`Export failed: ${(cause as Error).message}`); return }
    if (!output) return
    const writable = output.writable
    let rows = 0
    try {
      await writable.write(csvHeader(current.columns))
      const complete = await results.exportAll(tabKey, connectionId, current, async (page) => {
        rows += page.length
        await writable.write(csvRows(page))
      }, false)
      if (!complete) {
        await writable.abort()
        toast.show(current.exported?.incomplete ? 'Export interrupted — re-run the query to export again' : 'Export canceled because the connection or result changed')
        return
      }
      await writable.close()
      toast.show(current.limited ? `Exported first ${rows} of ${current.totalRowCount} rows to CSV (partial result)` : `Exported ${rows} row(s) to CSV`)
    } catch (cause) {
      await writable.abort().catch(() => undefined)
      toast.show(`Export failed: ${(cause as Error).message}`)
    }
  }
</script>

<!-- svelte-ignore a11y_no_static_element_interactions, a11y_click_events_have_key_events -->
<div class="results" data-component="svelte-results-panel">
  <div class="results-head">
    <div class="subtabs">
      {#each result?.grids ?? [] as current, index (current.key)}
        <button class="subtab" class:active={!result?.showMessages && result?.grid?.key === current.key} aria-pressed={!result?.showMessages && result?.grid?.key === current.key}
          title={`Statement ${current.statementNumber} · ${current.rows.length} loaded row(s)${current.limited ? ' · partial result' : ''}`} onclick={() => results.selectGrid(tabs.state.activeKey, current.key)}>Result {index + 1}</button>
      {/each}
      <button class="subtab" class:active={!result || result.showMessages} onclick={showMessagesView}>Messages</button>
    </div>
    <span class="spacer"></span>
    {#if result?.transactionOpen}
      <span class="txn-badge" title="A manual transaction is open for this tab">TXN</span>
      <button class="btn-sm commit" disabled={result.running || result.loadingMore} title="Commit the open transaction" onclick={() => runControl('COMMIT')}>COMMIT</button>
      <button class="btn-sm danger" disabled={result.running || result.loadingMore} title="Roll back the open transaction" onclick={() => runControl('ROLLBACK')}>ROLLBACK</button>
    {/if}
    {#if activeGrid}
      <button class="btn-sm" title="Copy loaded rows to clipboard (TSV)" disabled={result?.loadingMore} onclick={copyResult}><Copy size={13} /> COPY</button>
      <button class="btn-sm" title={activeGrid.limited ? 'Export only the retained rows to CSV (partial result)' : 'Export all rows to CSV'} disabled={result?.loadingMore} onclick={exportCsv}><Download size={13} /> {activeGrid.limited ? 'CSV (partial)' : 'CSV'}</button>
    {/if}
    {#if result?.running || result?.loadingMore}
      <button class="danger" disabled={result.cancelling} title="Cancel running query or row load" onclick={cancelRun}><Square size={11} /> {result.cancelling ? 'Canceling…' : result.loadingMore ? 'Cancel load' : 'Cancel'}</button>
    {:else}
      <button class="primary run-btn" disabled={!snapshot.current.connectionId || result?.loadingMore || snapshot.current.readOnly} title="Run (F5 or Ctrl+Enter)" onclick={onrun}><Play size={13} /> Run</button>
    {/if}
  </div>
  {#if !result || result.showMessages || !result.grid}
    <div class="messages">
      {#if !result || !result.messages.length}<div class="msg dim">Run a query to see results (F5 or Ctrl+Enter in the editor).</div>{/if}
      {#each result?.messages ?? [] as message, index (index)}<div class={`msg ${message.level}`}>{message.text}</div>{/each}
    </div>
  {:else if grid}
    <div class="grid">
      <div bind:this={bodyEl} class="grid-body" onscroll={() => { if (bodyEl) scrollTop = bodyEl.scrollTop }}>
        <div class="grid-inner" style:width={`${innerWidth}px`}>
          <div class="grid-head">
            {#if rowEditable}<div class="grid-cell head actions" style:width={`${ACTION_W}px`} title="Edit a row in a dialog (needs the full primary key in the result)"></div>{/if}
            {#each grid.g.columns as column, index (`${index}-${column}`)}
              <div class="grid-cell head" style:width={`${colWidth(index)}px`}>
                <span class="col-name">{column}</span>{#if grid.g.columnTypes[index]}<span class="col-type"> ({grid.g.columnTypes[index]})</span>{/if}
                <span class="col-resize-handle" title="Resize column" onmousedown={(event) => startResize(index, event)} onclick={(event) => event.stopPropagation()}></span>
              </div>
            {/each}
          </div>
          <div class="grid-spacer" style:height={`${grid.g.rows.length * ROW_H}px`}></div>
          {#each grid.rows as row, index (grid.start + index)}
            <div class="grid-row" style:top={`${HEADER_H + (grid.start + index) * ROW_H}px`}>
              {#if rowEditable}
                <div class="grid-cell actions" style:width={`${ACTION_W}px`}><button class="icon rowedit-open" title={rowKeyComplete(row) ? 'Edit row' : 'Row key is not available'} disabled={!rowKeyComplete(row)} onclick={() => { if (grid) openRowEdit(grid.start + index) }}><Pencil size={12} /></button></div>
              {/if}
              {#each row as cell, column (column)}
                <div class="grid-cell" class:nul={cell === null || cell === undefined} style:width={`${colWidth(column)}px`} title={isJsonColumn(column) ? 'Double-click to open value' : 'Double-click to copy'} ondblclick={() => openCell(cell, column)}>
                  {#if cell === null || cell === undefined}<span class="null-badge">null</span>
                  {:else if grid.g.columnTypes[column] === 'boolean'}<span class={`bool-badge ${cell === true || cell === 'true' ? 'true' : 'false'}`}>{cell === true || cell === 'true' ? 'true' : 'false'}</span>
                  {:else}{formatCellForDisplay(cell)}{/if}
                </div>
              {/each}
            </div>
          {/each}
        </div>
      </div>
      <div class="grid-foot">
        {result.grid?.rowCount ?? 0} row(s)
        {#if grid.g.truncated}<span>· more available</span>
        {:else if grid.g.limited}<span>· first {grid.g.rows.length}{#if grid.g.totalRowCount} of {grid.g.totalRowCount}{/if} · row limit reached; remaining rows were not retained</span>
        {:else if grid.g.exported?.incomplete}<span>· export interrupted — re-run the query</span>
        {:else if grid.g.exported}<span>· first {grid.g.rows.length} shown · {grid.g.exported.rows} row(s) exported to CSV</span>{/if}
        {#if grid.g.truncated}<button class="btn-sm" disabled={result.loadingMore} title="Fetch the next page of rows" onclick={loadMoreRows}>{result.loadingMore ? 'Loading…' : 'Load more'}</button>{/if}
      </div>
    </div>
  {/if}
  {#if cellValue}<ValueDialog target={cellValue} onclose={() => { cellValue = null }} />{/if}
  {#if rowEdit}<RowEditDialog target={rowEdit} onsaved={onRowSaved} onclose={() => { rowEdit = null }} />{/if}
</div>
